# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6
yarn_mappings=1.21.6+build.1
loader_version=0.16.14

# Mod Properties
mod_version = 1.4.0
maven_group = com.github.Provismet
archives_base_name = tooltip-scroll

# Dependencies
fabric_version=0.128.0+1.21.6
cloth_version=19.0.147
modmenu_version=15.0.0-beta.3
lilylib_version=4.0.0-mc1.21.5

# Publishing
github_repo=Tooltip-Scroll-Fabric
github_branch=1.21.2
modrinth_id=wySVd6d8
curseforge_id=495546
version_start=1.21.2
version_end=1.21.3