# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=1.5.1
maven_group=com.github.Provismet
archives_base_name=tooltip-scroll

# Dependencies
fabric_version=0.135.0+1.21.10
cloth_version=19.0.147
modmenu_version=16.0.0-rc.1
lilylib_version=4.0.1-mc1.21.10

# Publishing
github_repo=Tooltip-Scroll-Fabric
github_branch=1.21.10
modrinth_id=wySVd6d8
curseforge_id=495546
version_start=1.21.9
version_end=1.21.10