# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
yarn_mappings=1.21+build.2
loader_version=0.15.11

# Mod Properties
mod_version = 1.4.0
maven_group = com.provismet
archives_base_name = tooltip-scroll

# Dependencies
fabric_version=0.100.1+1.21
cloth_version=15.0.127
modmenu_version=11.0.0-rc.1
lilylib_version=1.2.1-mc1.21
